version: "3.8"

services:

  api: 
    image: ghcr.io/message-manager-discord/backend:2
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    command: >
      sh -c "npm run migrate && npm run start"

  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=passsadfl8jn3a01m
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts:/scripts
    ports:
      - 5432:5432

volumes:
  postgres-data: {}